# Generated by Django 4.2.26 on 2025-11-23 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('grade', models.IntegerField(choices=[(5, '5. Sınıf'), (6, '6. Sınıf'), (7, '7. Sınıf'), (8, '8. Sınıf')], verbose_name='Sınıf')),
                ('student_number', models.CharField(max_length=20, unique=True, verbose_name='Okul No')),
                ('parent_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Veli Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
                'ordering': ['grade', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='BedCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('is_tidy', models.BooleanField(default=True, verbose_name='Düzenli mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_checks', to='students.student')),
            ],
            options={
                'verbose_name': 'Yatak Kontrolü',
                'verbose_name_plural': 'Yatak Kontrolleri',
                'unique_together': {('student', 'date')},
            },
        ),
    ]
