# Generated by Django 4.2.26 on 2025-11-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('prayer_time', models.CharField(choices=[('sabah', 'Sabah'), ('ogle', 'Öğle'), ('ikindi', 'İkindi'), ('aksam', 'Akşam'), ('yatsi', 'Yatsı')], max_length=10, verbose_name='Namaz Vakti')),
                ('status', models.CharField(choices=[('geldi', 'Geldi'), ('gec_kaldi', 'Geç Kaldı'), ('gelmedi', 'Gelmedi'), ('mazeret', 'Mazeretli')], max_length=15, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_attendances', to='students.student')),
            ],
            options={
                'verbose_name': 'Namaz Devamsızlık Kaydı',
                'verbose_name_plural': 'Namaz Devamsızlık Kayıtları',
                'ordering': ['date', 'prayer_time', 'student'],
                'unique_together': {('student', 'date', 'prayer_time')},
            },
        ),
    ]
