# Generated by Django 4.2.26 on 2025-11-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_prayerattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('session_type', models.CharField(choices=[('etut', 'Etüt'), ('dini_ders', 'Dini Ders')], max_length=15, verbose_name='Oturum Türü')),
                ('performance', models.CharField(choices=[('mukemmel', 'Mükemmel'), ('iyi', 'İyi'), ('orta', 'Orta'), ('zayif', 'Zayıf'), ('katilmadi', 'Katılmadı')], max_length=15, verbose_name='Performans')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_performances', to='students.student')),
            ],
            options={
                'verbose_name': 'Etüt/Ders Performansı',
                'verbose_name_plural': 'Etüt/Ders Performansları',
                'ordering': ['date', 'session_type', 'student'],
                'unique_together': {('student', 'date', 'session_type')},
            },
        ),
    ]
