# Generated by Django 4.2.26 on 2025-11-23 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studyperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ders Adı')),
                ('grade', models.IntegerField(verbose_name='Sınıf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
                'ordering': ['grade', 'name'],
                'unique_together': {('name', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('yazili_1', '1. Yazılı'), ('yazili_2', '2. Yazılı'), ('sozlu', 'Sözlü'), ('performans', 'Performans/Proje')], max_length=20, verbose_name='Sınav Türü')),
                ('term', models.CharField(choices=[('donem_1', '1. Dönem'), ('donem_2', '2. Dönem')], max_length=10, verbose_name='Dönem')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Not (0-100)')),
                ('exam_date', models.DateField(verbose_name='Sınav Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.subject', verbose_name='Ders')),
            ],
            options={
                'verbose_name': 'Sınav',
                'verbose_name_plural': 'Sınavlar',
                'ordering': ['-exam_date', 'student'],
                'unique_together': {('student', 'subject', 'exam_type', 'term')},
            },
        ),
    ]
