# Generated by Django 6.0.3 on 2026-03-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyperformance',
            name='performance',
            field=models.CharField(choices=[('mukemmel', 'Mükemmel'), ('iyi', 'İyi'), ('orta', 'Orta'), ('zayif', 'Zayıf'), ('katilmadi', 'Katılmadı'), ('izinli', 'İzinli')], max_length=15, verbose_name='Performans'),
        ),
    ]
