# Generated by Django 4.0.4 on 2025-12-30 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'Yüksek (Kırmızı)')], default='normal', max_length=10, verbose_name='Öncelik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('hadith', 'Hadis-i Şerif'), ('verse', 'Ayet-i Kerime'), ('word', 'Günün Sözü')], max_length=10, verbose_name='Tür')),
                ('text', models.TextField(verbose_name='Metin')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='Kaynak (Sure/Ravi)')),
                ('date_to_show', models.DateField(default=django.utils.timezone.now, verbose_name='Gösterilecek Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Günün İçeriği',
                'verbose_name_plural': 'Günün İçerikleri',
                'ordering': ['-date_to_show'],
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Başlık')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider_images/', verbose_name='Görsel')),
                ('video', models.FileField(blank=True, null=True, upload_to='slider_videos/', verbose_name='Video')),
                ('display_duration', models.IntegerField(default=10, verbose_name='Gösterim Süresi (Saniye)')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider Ögesi',
                'verbose_name_plural': 'Slider Ögeleri',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
